[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "r4u"
version = "0.1.0"
description = "Observability SDK for LLM applications"
readme = "README.md"
authors = [{name = "R4U Team"}]
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "httpx>=0.24.0",
    "openai>=2.2.0",
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
openai = ["openai>=1.0.0"]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.10.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
