"""add_prompt_variables_to_trace

Revision ID: 000cc9671af9
Revises: c8ea798be286
Create Date: 2025-10-23 15:15:22.259203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000cc9671af9'
down_revision: Union[str, Sequence[str], None] = 'c8ea798be286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace', sa.Column('prompt_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trace', 'prompt_variables')
    # ### end Alembic commands ###
