"""add_request_parameters_to_tasks

Revision ID: 0de4274850ee
Revises: 6e7f0392eb1e
Create Date: 2025-10-17 16:48:10.900157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0de4274850ee'
down_revision: Union[str, Sequence[str], None] = '6e7f0392eb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('task', sa.Column('tool_choice', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('task', sa.Column('reasoning', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'reasoning')
    op.drop_column('task', 'tool_choice')
    op.drop_column('task', 'temperature')
    op.drop_column('task', 'instructions')
    # ### end Alembic commands ###
