"""add_http_trace_table

Revision ID: 105bd027cb07
Revises: dd2f7ffcfe5a
Create Date: 2025-10-22 20:10:33.579861

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "105bd027cb07"
down_revision: str | Sequence[str] | None = "dd2f7ffcfe5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "http_trace",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("request", sa.Text(), nullable=False),
        sa.Column(
            "request_headers",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                "postgresql",
            ),
            nullable=False,
        ),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column(
            "response_headers",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                "postgresql",
            ),
            nullable=False,
        ),
        sa.Column(
            "http_metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                "postgresql",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_http_trace")),
    )
    op.create_index(
        op.f("ix_http_trace_started_at"),
        "http_trace",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_http_trace_status_code"),
        "http_trace",
        ["status_code"],
        unique=False,
    )
    op.add_column("trace", sa.Column("http_trace_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_trace_http_trace_id_http_trace"),
        "trace",
        "http_trace",
        ["http_trace_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_trace_http_trace_id_http_trace"),
        "trace",
        type_="foreignkey",
    )
    op.drop_column("trace", "http_trace_id")
    op.drop_index(op.f("ix_http_trace_status_code"), table_name="http_trace")
    op.drop_index(op.f("ix_http_trace_started_at"), table_name="http_trace")
    op.drop_table("http_trace")
    # ### end Alembic commands ###
