"""Add http_path and http_method to http_trace

Revision ID: 2e10e12d3f5b
Revises: dcf37b064cb9
Create Date: 2025-11-28 16:08:00.832761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e10e12d3f5b'
down_revision: Union[str, Sequence[str], None] = 'dcf37b064cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('http_trace', sa.Column('request_method', sa.Text(), nullable=True))
    op.add_column('http_trace', sa.Column('request_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('http_trace', 'request_path')
    op.drop_column('http_trace', 'request_method')
    # ### end Alembic commands ###
