"""Add name and description to tasks

Revision ID: 37309a4b1b2f
Revises: f58158b8ecde
Create Date: 2025-10-30 18:18:08.266414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37309a4b1b2f'
down_revision: Union[str, Sequence[str], None] = 'f58158b8ecde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_result_evaluation_id'), table_name='execution_result')
    op.drop_index(op.f('ix_execution_result_test_case_id'), table_name='execution_result')
    op.add_column('task', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'description')
    op.drop_column('task', 'name')
    op.create_index(op.f('ix_execution_result_test_case_id'), 'execution_result', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_execution_result_evaluation_id'), 'execution_result', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###
