"""add_trace_request_parameters_and_reasoning

Revision ID: 5cd8050268df
Revises: 2ab7f18e5ff7
Create Date: 2025-10-17 15:57:06.066692

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5cd8050268df"
down_revision: str | Sequence[str] | None = "2ab7f18e5ff7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trace", sa.Column("instructions", sa.Text(), nullable=True))
    op.add_column("trace", sa.Column("prompt", sa.Text(), nullable=True))
    op.add_column("trace", sa.Column("temperature", sa.Float(), nullable=True))
    op.add_column("trace", sa.Column("tool_choice", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True))
    op.add_column("trace", sa.Column("reasoning", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trace", "reasoning")
    op.drop_column("trace", "tool_choice")
    op.drop_column("trace", "temperature")
    op.drop_column("trace", "prompt")
    op.drop_column("trace", "instructions")
    # ### end Alembic commands ###
