"""Remove project_id field from http-trace

Revision ID: 94fea38d9635
Revises: 8b6699fbf9aa
Create Date: 2025-11-12 16:43:51.884147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fea38d9635'
down_revision: Union[str, Sequence[str], None] = '8b6699fbf9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_http_trace_project_id_project'), 'http_trace', type_='foreignkey')
    op.drop_column('http_trace', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('http_trace', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_http_trace_project_id_project'), 'http_trace', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
