"""Add max_tokens to trace

Revision ID: 956d760ec79d
Revises: 3231e64230a3
Create Date: 2025-10-24 18:08:26.134657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956d760ec79d'
down_revision: Union[str, Sequence[str], None] = '3231e64230a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace', sa.Column('max_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trace', 'max_tokens')
    # ### end Alembic commands ###
