"""Add provider and model tables

Revision ID: a4fe3ce0bf4f
Revises: dfaa9df466bf
Create Date: 2025-11-06 20:50:01.632200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4fe3ce0bf4f'
down_revision: Union[str, Sequence[str], None] = 'dfaa9df466bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider')),
    sa.UniqueConstraint('name', name=op.f('uq_provider_name'))
    )
    op.create_index('ix_provider_name', 'provider', ['name'], unique=True)
    op.create_table('model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('fk_model_provider_id_provider'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model')),
    sa.UniqueConstraint('provider_id', 'name', name='uq_model_provider_name')
    )
    op.create_index('ix_model_provider_id', 'model', ['provider_id'], unique=False)
    op.drop_column('execution_result', 'tool_calls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_result', sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('ix_model_provider_id', table_name='model')
    op.drop_table('model')
    op.drop_index('ix_provider_name', table_name='provider')
    op.drop_table('provider')
    # ### end Alembic commands ###
