"""Add path to trace table

Revision ID: aaa838502c9d
Revises: 7bb407e66f29
Create Date: 2025-10-14 13:58:01.895826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa838502c9d'
down_revision: Union[str, Sequence[str], None] = '7bb407e66f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace', sa.Column('path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trace', 'path')
    # ### end Alembic commands ###
