"""add_tokens_schema_metadata_to_traces

Revision ID: c166fc620924
Revises: 33070573efab
Create Date: 2025-10-15 16:52:16.197682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c166fc620924'
down_revision: Union[str, Sequence[str], None] = '33070573efab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_project_name'), 'project', ['name'])
    op.add_column('trace', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('trace', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('trace', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('trace', sa.Column('response_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('trace', sa.Column('trace_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trace', 'trace_metadata')
    op.drop_column('trace', 'response_schema')
    op.drop_column('trace', 'total_tokens')
    op.drop_column('trace', 'completion_tokens')
    op.drop_column('trace', 'prompt_tokens')
    op.drop_constraint(op.f('uq_project_name'), 'project', type_='unique')
    # ### end Alembic commands ###
