"""change_traces_to_reference_implementations

Revision ID: c8ea798be286
Revises: 105bd027cb07
Create Date: 2025-10-23 14:56:11.036909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ea798be286'
down_revision: Union[str, Sequence[str], None] = '105bd027cb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace', sa.Column('implementation_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_trace_task_id'), table_name='trace')
    op.create_index('ix_trace_implementation_id', 'trace', ['implementation_id'], unique=False)
    op.drop_constraint(op.f('fk_trace_task_id_task'), 'trace', type_='foreignkey')
    op.create_foreign_key(op.f('fk_trace_implementation_id_implementation'), 'trace', 'implementation', ['implementation_id'], ['id'], ondelete='SET NULL')
    op.drop_column('trace', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_trace_implementation_id_implementation'), 'trace', type_='foreignkey')
    op.create_foreign_key(op.f('fk_trace_task_id_task'), 'trace', 'task', ['task_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_trace_implementation_id', table_name='trace')
    op.create_index(op.f('ix_trace_task_id'), 'trace', ['task_id'], unique=False)
    op.drop_column('trace', 'implementation_id')
    # ### end Alembic commands ###
