"""Update trace.output

Revision ID: ee91575c2c42
Revises: 00d6b6e483a7
Create Date: 2025-10-29 19:11:37.630654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee91575c2c42'
down_revision: Union[str, Sequence[str], None] = '00d6b6e483a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace_output_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['trace.id'], name=op.f('fk_trace_output_item_trace_id_trace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trace_output_item'))
    )
    op.create_index('ix_trace_output_item_trace_id_position', 'trace_output_item', ['trace_id', 'position'], unique=True)
    op.create_index('ix_trace_output_item_type', 'trace_output_item', ['type'], unique=False)
    op.drop_column('trace', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace', sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('ix_trace_output_item_type', table_name='trace_output_item')
    op.drop_index('ix_trace_output_item_trace_id_position', table_name='trace_output_item')
    op.drop_table('trace_output_item')
    # ### end Alembic commands ###
